- first_name: John
  last_name: Doe
  phone: "8000"
  account_index: 1
  group_id: 0
- first_name: Lily
  last_name: Lee
  phone: "6000"
  account_index: 2
  group_id: 2
- first_name: Amir
  last_name: Khan
  phone: "+1 555 0101"
  account_index: 1
  group_id: 1
